export const metadata = {
    title: "Reserve at MileStone Grill {Torronto} | OpenTable",
    description: "Generated by create next app",
  };
  
  export default function RestaurantLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return <main>{children}</main>;
  }
  