export const metadata = {
  title: "Search Restaurant OpenTable",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
